In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import json


In [2]:
df=pd.read_csv('medical_insurance.csv')
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [3]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [5]:
df['sex'].replace({'female':0,'male':1},inplace=True)

In [6]:
df['smoker'].value_counts()

no     1064
yes     274
Name: smoker, dtype: int64

In [7]:
df['smoker'].replace({'no':1,'yes':0},inplace=True)

In [8]:
df['region'].value_counts().to_dict()

{'southeast': 364, 'southwest': 325, 'northwest': 325, 'northeast': 324}

In [9]:

df=pd.get_dummies(df,columns=['region'])
df

age  sex     bmi  children  smoker      charges  region_northeast  \
0      19    0  27.900         0       0  16884.92400                 0   
1      18    1  33.770         1       1   1725.55230                 0   
2      28    1  33.000         3       1   4449.46200                 0   
3      33    1  22.705         0       1  21984.47061                 0   
4      32    1  28.880         0       1   3866.85520                 0   
...   ...  ...     ...       ...     ...          ...               ...   
1333   50    1  30.970         3       1  10600.54830                 0   
1334   18    0  31.920         0       1   2205.98080                 1   
1335   18    0  36.850         0       1   1629.83350                 0   
1336   21    0  25.800         0       1   2007.94500                 0   
1337   61    0  29.070         0       0  29141.36030                 0   

      region_northwest  region_southeast  region_southwest  
0                    0                 0                 1  
1                    0                 1                 0  
2                    0                 1                 0  
3                    1                 0                 0  
4                    1                 0                 0  
...                ...               ...               ...  
1333                 1                 0                 0  
1334                 0                 0                 0  
1335                 0                 1                 0  
1336                 0                 0                 1  
1337                 1                 0                 0  

[1338 rows x 10 columns]

In [10]:


df['children'].value_counts()

0    574
1    324
2    240
3    157
4     25
5     18
Name: children, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               1338 non-null   int64  
 1   sex               1338 non-null   int64  
 2   bmi               1338 non-null   float64
 3   children          1338 non-null   int64  
 4   smoker            1338 non-null   int64  
 5   charges           1338 non-null   float64
 6   region_northeast  1338 non-null   uint8  
 7   region_northwest  1338 non-null   uint8  
 8   region_southeast  1338 non-null   uint8  
 9   region_southwest  1338 non-null   uint8  
dtypes: float64(2), int64(4), uint8(4)
memory usage: 68.1 KB


# Train Test Split

In [12]:
x=df.drop('charges',axis=1)
y=df['charges']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=5)

In [13]:
x_train

age  sex     bmi  children  smoker  region_northeast  region_northwest  \
1261   28    1  37.100         1       1                 0                 0   
816    24    0  24.225         0       1                 0                 1   
581    19    1  30.590         0       1                 0                 1   
1328   23    0  24.225         2       1                 1                 0   
492    18    0  25.080         0       1                 1                 0   
...   ...  ...     ...       ...     ...               ...               ...   
73     58    1  32.010         1       1                 0                 0   
1142   52    0  24.860         0       1                 0                 0   
998    33    0  36.290         3       1                 1                 0   
206    59    1  26.400         0       1                 0                 0   
867    57    1  43.700         1       1                 0                 0   

      region_southeast  region_southwest  
1261                 0                 1  
816                  0                 0  
581                  0                 0  
1328                 0                 0  
492                  0                 0  
...                ...               ...  
73                   1                 0  
1142                 1                 0  
998                  0                 0  
206                  1                 0  
867                  0                 1  

[1070 rows x 9 columns]

# M0odel Training

In [14]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [15]:
y_pred=model.predict(x_test) #testing data evaluation
y_pred[20:25]

array([28608.5344058 ,  2192.40931861,  3243.54449102,  3794.92040149,
        2490.18568536])

In [16]:
mse=mean_squared_error(y_test,y_pred)
print('MSE is :',mse)

rmse=np.sqrt(mse)
print('RMSE is :',rmse)

mae=mean_absolute_error(y_test,y_pred)
print('MAE is :',mae)

r2=r2_score(y_test,y_pred)
print('R-squared is :',r2)

MSE is : 33680468.38188878
RMSE is : 5803.487605043089
MAE is : 3920.3167916738407
R-squared is : 0.7781096604223829


In [17]:
#training Data Evaluation
y_pred_train=model.predict(x_train)

mse=mean_squared_error(y_train,y_pred_train)
print('MSE is :',mse)

rmse=np.sqrt(mse)
print('RMSE is :',rmse)

mae=mean_absolute_error(y_train,y_pred_train)
print('MAE is :',mae)

r2=r2_score(y_train,y_pred_train)
print('R-squared is :',r2)

MSE is : 37266065.520491056
RMSE is : 6104.593804708963
MAE is : 4283.144379205723
R-squared is : 0.7430471855293475


# Testing on single row

In [18]:
x.head(1).T

0
age               19.0
sex                0.0
bmi               27.9
children           0.0
smoker             0.0
region_northeast   0.0
region_northwest   0.0
region_southeast   0.0
region_southwest   1.0

In [19]:
age=25
sex='male'
bmi=27.9
children= 3
smoker='no'
region_northeast='northeast'

In [20]:
project_data={'sex':{'female':0,'male':1},
                   "smoker":{'no':1,'yes':0},
                   "columns":list(x.columns)}
project_data['sex'][sex]

1

In [21]:
column_names=x.columns
region='region_'+'northeast'
region_index=np.where(column_names == region)[0][0]
region_index
column_names

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region_northeast',
       'region_northwest', 'region_southeast', 'region_southwest'],
      dtype='object')

In [22]:
test_array=np.zeros(x.shape[1])
test_array[0]=age
test_array[1]=project_data['sex'][sex]
test_array[2]=bmi
test_array[3]=children
test_array[4]=project_data['smoker'][smoker]
test_array[region_index]=1
test_array

array([25. ,  1. , 27.9,  3. ,  1. ,  1. ,  0. ,  0. ,  0. ])

In [23]:
model.predict([test_array])

array([5257.600074])

In [24]:
with open('Linear_Model.pkl','wb') as f:
    pickle.dump(model,f)

In [25]:
with open("project_data.json",'w') as f:
    json.dump(project_data,f)

In [26]:
# def get_predicted_charges()

In [ ]:
#GIT